### ISSUE TITLE
max 500 reviews on app_store_reviews_reader

### ISSUE THREAD

**Issue by plfreegard** [lalitpagaria/app_store_reviews_reader#3]
Just trying to use your useful tool to retrieve App Store reviews.  It seems to get stuck when asking for more than 500 reviews.  When it reaches the last page (seems to be page10) it simply repeats it, even though there are many more reviews to be had.  

Do you have any idea what is happening?

eg
import pprint
from datetime import datetime, timedelta

import pytz as pytz

from my_appstorereviewreader import AppStoreReviewsReader

# app_id, and country of xcode
reader = AppStoreReviewsReader(
    app_id="565993818",
    country="gb"
)
reviews = reader.fetch_reviews()

**Comment by lalitpagaria** [comment]
Thanks for reporting issue.
Can you share sample code or steps to reproduce this issue.

**Comment by plfreegard** [comment]
sure.  I dropped this into the code to see what was happening when it got into a loop - you can see that it keeps repeating the same 'next page'.  the same last 50 records are repeated.
            if feed.feed.links is not None:
                for link in feed.feed.links:
                    if link.get('rel', '') == 'next':
                        feed_url = link.href
                        print('Next page number: ',link.href.split('/')[6] )
                        has_next = True
                        break

**Comment by lalitpagaria** [comment]
Thank you for reporting this, yes there was infinite loop was there.
I have pushed the fix on master (https://github.com/lalitpagaria/app_store_reviews_reader/commit/0d541c8e061ece556d6b18816e7e40bfaa3aff94) branch can you please test and let me know.

**Comment by lalitpagaria** [comment]
Can you please try with latest changes and reopen if you still see this issue
