### ISSUE TITLE
Reviews Not seeing the correct number of records and loop for <50 records

### ISSUE THREAD

**Issue by plfreegard** [lalitpagaria/app_store_reviews_reader#4]
still not sure its working fully.  
1. Firstly its returning 450 records - with 10 pages returned should that be 500 reviews - is it missing the final page.   Not sure of this was testing with 'gb', app_id='1220329065'
2. its not working where the reviews are less than 50 on a page ie 1 or two.  try it with 'gb' app_id ='1458113535'

**Comment by lalitpagaria** [comment]
Oh okay
There was infinite loop issue which I fixed but it might have introduced another bug.
Thanks for reporting it and sharing test app_id. I will fix it.

**Comment by lalitpagaria** [comment]
@plfreegard Can you please try now. I have tested on both the examples you shared. Reopen this issue if not still face issue.
https://github.com/lalitpagaria/app_store_reviews_reader/commit/8f81a3408533cb7b6a881fce830d6c7cbd17391f
